### PR TITLE
Async Task Completion

### PR DESCRIPTION
**Pull request by xplodedthemes**
Since the task contains asynchronous cod, we need to signal gulp when the task has finished executing (= "async completion").
This will remove the message "Did you forget to signal async completion?"

### CODE REVIEW

**Comment by alanef** [comment]
James can this be merged, as it just shows up in Gulp 4

**Comment by ernilambar** [comment]
@xplodedthemes @alanef Since the repo is not active since long, I have copied the code and fixed few bugs. If you are still looking for it then you can try this https://github.com/ernilambar/gulp-freemius-deployer

**Comment by alanef** [comment]
Nice will give ita go

**Comment by jamesckemp** [comment]
Sorry, missed this! We just merged a similar PR #6

**Pull request closed without merging**
